spring:
 datasource:
   driver-class-name: org.mariadb.jdbc.Driver
   url: jdbc:mariadb://192.168.100.100:3306/prod
   username: user01
   password: user01
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       format_sql: true
